const data = [
  {
    id: 1,
    country: "USA",
    runtime: "2016",
    title: "Stranger Things",
    rating: "86.0/100",
    tomatoRating: "97%",
    tvSeries: true,
    genre: "Action, Adventure",
  },
  {
    id: 2,
    country: "UK",
    runtime: "2018",
    title: "The Crown",
    rating: "90.0/100",
    tomatoRating: "95%",
    genre: "Drama, History",
  },
  {
    id: 3,
    country: "Canada",
    runtime: "2019",
    title: "Schitt's Creek",
    rating: "95.0/100",
    tomatoRating: "98%",
    genre: "Comedy",
  },
  {
    id: 4,
    country: "Spain",
    runtime: "2020",
    title: "Money Heist",
    rating: "92.0/100",
    tomatoRating: "93%",
    tvSeries: true,
    genre: "Action, Crime, Mystery",
  },
  {
    id: 5,
    country: "Australia",
    runtime: "2017",
    title: "The Babadook",
    rating: "89.0/100",
    tomatoRating: "96%",
    genre: "Horror, Drama",
  },
  {
    id: 6,
    country: "France",
    runtime: "2021",
    title: "Lupin",
    rating: "88.0/100",
    tomatoRating: "94%",
    genre: "Crime, Drama, Mystery",
  },
  {
    id: 7,
    country: "Germany",
    runtime: "2015",
    title: "Dark",
    rating: "91.0/100",
    tomatoRating: "90%",
    tvSeries: true,
    genre: "Crime, Drama, Mystery",
  },
  {
    id: 8,
    country: "Japan",
    runtime: "2022",
    title: "Squid Game",
    rating: "93.0/100",
    tomatoRating: "92%",
    tvSeries: true,
    genre: "Drama, Thriller",
  },
  {
    id: 9,
    country: "South Korea",
    runtime: "2019",
    title: "Crash Landing on You",
    rating: "94.0/100",
    tomatoRating: "91%",
    genre: "Comedy, Romance",
  },
  {
    id: 10,
    country: "Brazil",
    runtime: "2018",
    title: "3%",
    rating: "87.0/100",
    tomatoRating: "89%",
    tvSeries: true,
    genre: "Drama, Sci-Fi, Thriller",
  },
  {
    id: 11,
    country: "USA",
    runtime: "2018",
    title: "Spider-Man : Into The Spider Verse",
    rating: "84.0/100",
    tomatoRating: "87%",
    genre: "Animation, Action, Adventure",
  },
  {
    id: 12,
    country: "USA",
    runtime: "2017",
    title: "Dunkirk",
    rating: "78.0/100",
    tomatoRating: "94%",
    genre: "Action, Drama, History",
  },
];

export default data;
